services:

  ipfs:
    image: ipfs/kubo:latest
    container_name: ipfs
    volumes:
      - ./ipfs_path:/data/ipfs
      - ./ipfs_export:/export
      - ./ipfs_fuse:/ipfs
      - ./ipns_fuse:/ipns     
    ports:
      - "4001:4001/tcp"
      - "4001:4001/udp"
      - "5001:5001"
      - "8080:8080"
    restart: unless-stopped
    environment:
      - IPFS_PATH=/data/ipfs
